### PR TITLE
fix: Use `evalaute_script` if the driver has it available

### LINKED ISSUE #150: Issues with Apparition driver in 4.3.x
We just did consecutive builds with 4.3.0 and 4.3.1. The 4.3.1 build had every CI job end with this output:

```

[percy] stopping percy...
--
  | [percy] waiting for 0 snapshots to complete...
  | [percy] done.

```

### PR DESCRIPTION
**Pull request by Robdel12**
## What is this?

This is to avoid any issues where Capybara drivers don't return the value from `execute_script`

Will close #150

### CODE REVIEW

File: lib/percy.rb [hunk 1]
```diff
@@ -128,4 +139,8 @@ def self._keys_to_json(options)
   def self._is_debug?
     ENV['LOG_LEVEL'] == 'debug'
   end
+
+  def self._driver_has_evalaute?(driver)
+    driver.respond_to?('evaluate_script')
+  end
```
Comment (wwilsman) [inline lib/percy.rb:145]: Any reason for this being a separate method rather than just the one line in the condition?

**Comment by geoffharcourt** [comment]
@Robdel12 thank you for making this change!

**Comment by Robdel12** [comment]
No problem! Sorry for breaking it 😅
